baseURL = 'https://buckeyekettlebellclub.netlify.app'
languageCode = 'en-us'
title = 'Buckeye Kettlebell Club'

[module]
    [module.hugoVersion]
        extended = true
        min = "0.119.0"
    [[module.imports]]
        path = 'github.com/alex-shpak/hugo-book'
